server:
  port: 8210
  servlet:
    context-path: /credentials

application:
  gateway:
    host: ${GATEWAY_HOST}
    client-id: ${GATEWAY_CLIENT_ID}
    client-secret: ${GATEWAY_CLIENT_SECRET}
    issuing:
      par-endpoint: https://${application.gateway.host}/issuing/par
      authorize-endpoint: https://${application.gateway.host}/issuing/authorize?client_id=${application.gateway.client-id}
      token-endpoint: https://${application.gateway.host}/issuing/token
      token:
        audience: https://${application.gateway.host}/issuing
        issuer: ${application.gateway.client-id}
        signing-key: ${GATEWAY_TOKEN_SIGNING_KEY}
      redirect-uri: ${GATEWAY_ISSUING_REDIRECT_URI}
    verification:
      identity-endpoint: https://${application.gateway.host}/connect/authorize?client_id=${application.gateway.client-id}&response_type=code&redirect_uri=${application.gateway.verification.redirect-uri}&response_mode=query&scope=openid+Identity
      token-endpoint: https://${application.gateway.host}/connect/token
      redirect-uri: ${GATEWAY_VERIFICATION_REDIRECT_URI:https://jwt.ms} # http://local.tis-selfservice.com/credentials/api/verify/identity/callback}
  signature:
    secret-key: ${SIGNATURE_SECRET_KEY}

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:}
